/*
 * This file is part of the eslint-config-cowtech npm package. Copyright (C) 2017 and above Shogun <shogun@cowtech.it>.
 * Licensed under the MIT license, which can be found at http://www.opensource.org/licenses/mit-license.php.
 */

const DISABLED = 0;
const WARN = 1;
const ERROR = 2;

const MAX_LINE_LENGTH = 160;
const MAX_STATEMENTS = 25;
const MAX_COMPLEXITY = 25;
const MAX_PARAMETERS = 6;
const MAX_DEPTH = 5;
const MAGIC_NUMBERS = [
  -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, // Commonly used base numbers
  25, 28, 30, 50, 100, 250, 1000, 5000, 10000, 1E6, 1E9, 3600, // Commonly used date/time related numbers
  // Common HTTP status codes
  200, 201, 202, 204, 205, 206,
  300, 301, 302, 304, 307, 308,
  400, 401, 403, 404, 405, 406, 408, 409, 410, 415, 422, 429, 499,
  500, 501, 502, 504, 599
];

module.exports = {
  env: {
    es6: true,
    node: true
  },
  parserOptions: {
    ecmaVersion: 2017
  },
  extends: "eslint:recommended",
  rules: {
    // Possible Errors: http://eslint.org/docs/rules/#possible-errors
    "no-await-in-loop": DISABLED,
    "no-compare-neg-zero": ERROR,
    "no-cond-assign": [ERROR, "except-parens"],
    "no-console": DISABLED,
    "no-constant-condition": WARN,
    "no-control-regex": DISABLED,
    "no-debugger": DISABLED,
    "no-dupe-args": ERROR,
    "no-dupe-keys": ERROR,
    "no-duplicate-case": ERROR,
    "no-empty": ERROR,
    "no-empty-character-class": ERROR,
    "no-ex-assign": ERROR,
    "no-extra-boolean-cast": ERROR,
    "no-extra-parens": DISABLED,
    "no-extra-semi": ERROR,
    "no-func-assign": DISABLED,
    "no-inner-declarations": [ERROR, "both"],
    "no-invalid-regexp": ERROR,
    "no-irregular-whitespace": ERROR,
    "no-obj-calls": ERROR,
    "no-prototype-builtins": DISABLED,
    "no-regex-spaces": ERROR,
    "no-sparse-arrays": ERROR,
    "no-template-curly-in-string": ERROR,
    "no-unexpected-multiline": ERROR,
    "no-unreachable": ERROR,
    "no-unsafe-finally": ERROR,
    "no-unsafe-negation": ERROR,
    "use-isnan": ERROR,
    "valid-jsdoc": [ERROR, {requireReturn: false}],
    "valid-typeof": [ERROR, {requireStringLiterals: true}],
    // Best Practices: http://eslint.org/docs/rules/#best-practices
    "accessor-pairs": ERROR,
    "array-callback-return": ERROR,
    "block-scoped-var": ERROR,
    "class-methods-use-this": DISABLED,
    "complexity": [ERROR, MAX_COMPLEXITY],
    "consistent-return": ERROR,
    "curly": [ERROR, "multi-or-nest"],
    "default-case": DISABLED,
    "dot-location": [ERROR, "property"],
    "dot-notation": ERROR,
    "eqeqeq": ERROR,
    "guard-for-in": ERROR,
    "no-alert": WARN,
    "no-caller": ERROR,
    "no-case-declarations": DISABLED,
    "no-div-regex": ERROR,
    "no-else-return": ERROR,
    "no-empty-function": ERROR,
    "no-empty-pattern": ERROR,
    "no-eq-null": ERROR,
    "no-eval": ERROR,
    "no-extend-native": DISABLED,
    "no-extra-bind": ERROR,
    "no-extra-label": ERROR,
    "no-fallthrough": ERROR,
    "no-floating-decimal": ERROR,
    "no-global-assign": WARN,
    "no-implicit-coercion": ERROR,
    "no-implicit-globals": ERROR,
    "no-implied-eval": ERROR,
    "no-invalid-this": DISABLED,
    "no-iterator": ERROR,
    "no-labels": ERROR,
    "no-lone-blocks": ERROR,
    "no-loop-func": ERROR,
    "no-magic-numbers": [ERROR, {ignore: MAGIC_NUMBERS}],
    "no-multi-spaces": ERROR,
    "no-multi-str": ERROR,
    "no-new-func": ERROR,
    "no-new-wrappers": ERROR,
    "no-new": ERROR,
    "no-octal": ERROR,
    "no-octal-escape": ERROR,
    "no-param-reassign": DISABLED,
    "no-proto": ERROR,
    "no-redeclare": ERROR,
    "no-restricted-properties": DISABLED,
    "no-return-assign": [ERROR, "except-parens"],
    "no-return-await": ERROR,
    "no-self-assign": ERROR,
    "no-script-url": ERROR,
    "no-self-compare": ERROR,
    "no-sequences": ERROR,
    "no-throw-literal": DISABLED,
    "no-unmodified-loop-condition": ERROR,
    "no-unused-expressions": ERROR,
    "no-unused-labels": ERROR,
    "no-useless-call": ERROR,
    "no-useless-concat": ERROR,
    "no-useless-escape": ERROR,
    "no-useless-return": ERROR,
    "no-void": ERROR,
    "no-warning-comments": WARN,
    "no-with": ERROR,
    "prefer-promise-reject-errors": WARN,
    "radix": [ERROR, "always"],
    "require-await": ERROR,
    "vars-on-top": ERROR,
    "wrap-iife": [ERROR, "inside"],
    "yoda": DISABLED,
    // Strict Mode: http://eslint.org/docs/rules/#strict-mode
    "strict": DISABLED,
    // Variables: http://eslint.org/docs/rules/#variables
    "init-declarations": ERROR,
    "no-catch-shadow": ERROR,
    "no-delete-var": ERROR,
    "no-label-var": ERROR,
    "no-restricted-globals": DISABLED,
    "no-shadow": ERROR,
    "no-shadow-restricted-names": ERROR,
    "no-undef": ERROR,
    "no-undef-init": ERROR,
    "no-undefined": ERROR,
    "no-unused-vars": [ERROR, {vars: "all", args: "after-used", caughtErrors: "none"}],
    "no-use-before-define": ERROR,
    // Node.js and CommonJS: http://eslint.org/docs/rules/#nodejs-and-commonjs
    "callback-return": [ERROR, ["callback", "cb"]],
    "global-require": DISABLED,
    "handle-callback-err": ERROR,
    "no-mixed-requires": ERROR,
    "no-new-require": ERROR,
    "no-path-concat": DISABLED,
    "no-process-env": DISABLED,
    "no-process-exit": WARN,
    "no-restricted-modules": DISABLED,
    "no-sync": DISABLED,
    // Stylistic Issues: http://eslint.org/docs/rules/#stylistic-issues
    "array-bracket-spacing": [ERROR, "never"],
    "block-spacing": [ERROR, "never"],
    "brace-style": [ERROR, "1tbs"],
    "camelcase": [ERROR, {properties: "always"}],
    "capitalized-comments": [ERROR, "always"],
    "comma-dangle": [ERROR, "never"],
    "comma-spacing": [ERROR, {before: false, after: true}],
    "comma-style": [ERROR, "last"],
    "computed-property-spacing": [ERROR, "never"],
    "consistent-this": [ERROR, "self"],
    "eol-last": ERROR,
    "func-call-spacing": [ERROR, "never"],
    "func-name-matching": ERROR,
    "func-names": DISABLED,
    "func-style": [ERROR, "expression"],
    "id-blacklist": DISABLED,
    "id-length": DISABLED,
    "id-match": DISABLED,
    "indent": [ERROR, ERROR, {SwitchCase: WARN}],
    "jsx-quotes": [ERROR, "prefer-double"],
    "key-spacing": [ERROR, {beforeColon: false, afterColon: true, mode: "strict"}],
    "keyword-spacing": [ERROR, {
      before: false, after: false,
      overrides: {
        let: {after: true}, const: {after: true}, of: {before: true, after: true}, in: {before: true, after: true}, throw: {after: true},
        case: {after: true}, return: {after: true},
        export: {after: true}, default: {after: true}, import: {after: true}, from: {before: true, after: true}, as: {before: true, after: true}
      }
    }],
    "line-comment-position": DISABLED,
    "linebreak-style": [ERROR, "unix"],
    "lines-around-comment": DISABLED,
    "lines-around-directive": [ERROR, "always"],
    "max-depth": [ERROR, MAX_DEPTH],
    "max-len": [ERROR, MAX_LINE_LENGTH, ERROR, {ignoreComments: true}],
    "max-lines": DISABLED,
    "max-nested-callbacks": [ERROR, MAX_DEPTH],
    "max-params": [ERROR, MAX_PARAMETERS],
    "max-statements": [ERROR, MAX_STATEMENTS],
    "max-statements-per-line": [ERROR, {max: ERROR}],
    "multiline-ternary": DISABLED,
    "new-cap": [ERROR, {newIsCap: true, capIsNew: true}],
    "new-parens": ERROR,
    "newline-after-var": DISABLED,
    "newline-before-return": DISABLED,
    "newline-per-chained-call": DISABLED,
    "no-array-constructor": ERROR,
    "no-bitwise": WARN,
    "no-continue": DISABLED,
    "no-inline-comments": DISABLED,
    "no-lonely-if": ERROR,
    "no-mixed-operators": DISABLED,
    "no-mixed-spaces-and-tabs": [ERROR, "smart-tabs"],
    "no-multi-assign": DISABLED,
    "no-multiple-empty-lines": [ERROR, {max: ERROR}],
    "no-negated-condition": DISABLED,
    "no-nested-ternary": WARN,
    "no-new-object": ERROR,
    "no-plusplus": DISABLED,
    "no-restricted-syntax": DISABLED,
    "no-tabs": ERROR,
    "no-ternary": DISABLED,
    "no-trailing-spaces": ERROR,
    "no-underscore-dangle": DISABLED,
    "no-unneeded-ternary": ERROR,
    "no-whitespace-before-property": ERROR,
    "nonblock-statement-body-position": [ERROR, "below"],
    "object-curly-newline": DISABLED,
    "object-curly-spacing": [ERROR, "never"],
    "object-property-newline": DISABLED,
    "one-var": DISABLED,
    "one-var-declaration-per-line": DISABLED,
    "operator-assignment": [ERROR, "always"],
    "operator-linebreak": [ERROR, "after"],
    "padded-blocks": [ERROR, "never"],
    "quote-props": [ERROR, "consistent-as-needed"],
    "quotes": [ERROR, "double", "avoid-escape"],
    "require-jsdoc": DISABLED,
    "semi": [ERROR, "always"],
    "semi-spacing": [ERROR, {before: false, after: true}],
    "sort-keys": DISABLED,
    "sort-vars": DISABLED,
    "space-before-blocks": [ERROR, "never"],
    "space-before-function-paren": [ERROR, "never"],
    "space-in-parens": [ERROR, "never"],
    "space-infix-ops": ERROR,
    "space-unary-ops": [ERROR, {words: true, nonwords: false}],
    "spaced-comment": [ERROR, "always"],
    "template-tag-spacing": [ERROR, "always"],
    "unicode-bom": DISABLED,
    "wrap-regex": ERROR,
    // ECMAScript 6: http://eslint.org/docs/rules/#ecmascript-6
    "arrow-body-style": [ERROR, "as-needed"],
    "arrow-parens": [ERROR, "as-needed"],
    "arrow-spacing": [ERROR, {before: true, after: true}],
    "constructor-super": DISABLED,
    "generator-star-spacing": [ERROR, {before: true, after: false}],
    "no-class-assign": ERROR,
    "no-confusing-arrow": [ERROR, {allowParens: true}],
    "no-const-assign": ERROR,
    "no-dupe-class-members": ERROR,
    "no-duplicate-imports": ERROR,
    "no-new-symbol": ERROR,
    "no-restricted-imports": DISABLED,
    "no-this-before-super": DISABLED,
    "no-useless-computed-key": ERROR,
    "no-useless-constructor": ERROR,
    "no-useless-rename": ERROR,
    "no-var": ERROR,
    "object-shorthand": [WARN, "always", {avoidExplicitReturnArrows: true}],
    "prefer-arrow-callback": DISABLED,
    "prefer-const": [ERROR, {destructuring: "all"}],
    "prefer-destructuring": DISABLED,
    "prefer-numeric-literals": ERROR,
    "prefer-rest-params": ERROR,
    "prefer-spread": ERROR,
    "prefer-template": ERROR,
    "require-yield": ERROR,
    "rest-spread-spacing": [ERROR, "never"],
    "sort-imports": DISABLED,
    "symbol-description": ERROR,
    "template-curly-spacing": [ERROR, "never"],
    "yield-star-spacing": [ERROR, "before"]
  }
};
